url: https://kb-holdings.de/
baseurl: /

# Site settings
title: K.B. Holding GmbH
email: blaschke@kb-holdings.de
description: "K.B. Holding GmbH ist Bauträger und Immobilienmanager in Raum OWL."


# Team names, titles and social links
people:
- name: Kris Blaschke
  pic: 1
  position: Geschäftsführer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Fabienne Peters
  pic: 2
  position: Immobilienmanagement
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Werner Reineke
  pic: 3
  position: Leiter Technik
